apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: images.caching.knative.dev
spec:
  group: caching.knative.dev
  names:
    kind: Image
    plural: images
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec holds the desired state of the Image (from the client).
          properties:
            image:
              description: Image is the name of the container image url to cache across
                the cluster.
              type: string
            imagePullSecrets:
              description: ImagePullSecrets contains the names of the Kubernetes Secrets
                containing login information used by the Pods which will run this
                container.
              items:
                type: object
              type: array
            serviceAccountName:
              description: 'ServiceAccountName is the name of the Kubernetes ServiceAccount
                as which the Pods will run this container.  This is potentially used
                to authenticate the image pull if the service account has attached
                pull secrets.  For more information: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account'
              type: string
          required:
          - image
          type: object
        status:
          description: Status communicates the observed state of the Image (from the
            controller).
          properties:
            conditions:
              description: Conditions communicates information about ongoing/complete
                reconciliation processes that bring the "spec" inline with the observed
                state of the world.
              items:
                properties:
                  lastTransitionTime:
                    description: We use VolatileTime in place of metav1.Time to exclude
                      this from creating equality.Semantic differences (all other
                      things held constant).
                    type: object
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
